services:
  - type: web
    name: bankpro-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: COOKIE_SAME_SITE
        value: None
